### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by emresaracoglu** [undead25/alerty#1]
Hello
I get this error, can you help me?

> TypeError: document.getElementById(...) is null

**Comment by undead25** [comment]
could you paste your code?

**Comment by undead25** [comment]
Also your browser and version, Thanks for your issue.

**Comment by emresaracoglu** [comment]
Hello

Thank you for return,
1. Dont have all button in the one page, if dont have all buttons, I get this error

> TypeError: document.getElementById(...) is null
1. I have been using one button in Content.php page and working but if I have multiple button same ID in the a page then only a button is working.. Others buttons is not working

I use 4 same button (button ID=bekleyin) in Content.php but only one button is working
http://pastebin.com/SFWNZs7i _// delete by me_

Firefox 48

**Comment by undead25** [comment]
In one page, The ID is unique.
you have used jquery, so you can call alerty like this

``` js
$('#Bekleyin').on('click', function(event) {
  alerty.toasts('Please wait..', {bgColor: '#00A651', fontColor: '#fff', time:5550, place: 'top'})
})
```

but first you shoud chage your ID different, such as Bekleyin01...

if toasts content is same you can call alerty with class selector

**Comment by emresaracoglu** [comment]
I changed codes:

> $('#Bekleyin<?php echo $row["id"];?>').on('click', function(event) { ...

Thanks! 
BTW I ask one more question please
I want the show automatically without clicking any button. How do I show automatically when the page load?

**Comment by undead25** [comment]
first import alerty.js, then call it

``` js
// directly
alerty.toasts('Please wait..')
// or
window.onload = function(){
  alerty.toasts('Please wait..')
}
```

**Comment by emresaracoglu** [comment]
Yes, working now, you are great man! I like it this project, I following
Thank you for your time,
from Turkey

**Comment by undead25** [comment]
That's fine, thanks for your using.
