### ISSUE TITLE
Re-Size

### ISSUE THREAD

**Issue by emresaracoglu** [undead25/alerty#2]
I did not see the document size feature. I wonder, is it possible in future version size feature?

For example; 

> .. place: 'bottom', height:'40px', width:'80px', ..

**Comment by undead25** [comment]
Toasts style is under the guide of google material design, [snackbars-toasts-specs](https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-specs)

If, it is global(all toasts is same), you can customize the sass(if build with gulp)/css file.

Next version will add this to options, and also add iOS HUD toasts style.

Thanks for your suggestion. If more, please let me know.

**Comment by emresaracoglu** [comment]
I thank you,
I wish happy days
